[platformio]
default_envs = cardputer-adv

[env:cardputer-adv]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
board_upload.flash_size = 8MB
board_build.partitions = partitions.csv
upload_speed = 460800
monitor_speed = 115200
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCORE_DEBUG_LEVEL=0
lib_deps =
    m5stack/M5Cardputer@1.1.1
    m5stack/M5Unified@0.2.21
    m5stack/M5GFX@0.2.28
    arduino-irremote/IRremote@4.7.1
