#!/usr/bin/env python3
"""Generate offline English PCM assets with macOS Samantha, plus original toy SFX.

Requires macOS `say` and ffmpeg; normal builds use the committed generated assets.
No cloud service, credentials, or runtime speech synthesis required.
"""
import array
import hashlib
import json
import math
from pathlib import Path
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
RATE = 16000
SPEECH_RATE = 135
SPEECH_GAIN = 0.65


def run(args):
    subprocess.run(args, check=True)


def emit_pcm(path, symbol, samples):
    values = list(samples)
    lines = [f'alignas(4) const int16_t {symbol}[] = {{']
    for i in range(0, len(values), 24):
        lines.append(','.join(map(str, values[i:i + 24])) + ',')
    lines.append('};')
    path.write_text('\n'.join(lines) + '\n')
    return len(values)


def effect(kind, note):
    # A quiet C-major pentatonic palette, an octave below the original sounds.
    # Keep enough midrange for the small speaker without piercing high chirps.
    base = [261.63, 293.66, 329.63, 392.0, 440.0][note]
    length = int(RATE * [0.32, 0.36, 0.30, 0.42][kind])
    phase = 0.0
    out = []
    for i in range(length):
        t = i / RATE
        u = i / (length - 1)
        # Tiny drift gives a rounded water-drop character, without a whistle.
        freq = base * (1 + .07 * math.exp(-t * 16)) if kind == 0 else base
        phase += 2 * math.pi * freq / RATE
        attack = [0.030, 0.045, 0.022, 0.055][kind]
        envelope = math.sin(min(1, t / attack) * math.pi / 2) ** 2
        envelope *= (1 - u) ** 2 * math.exp(-t * 2)
        if kind == 0:    # rounded water drop, nearly pure sine
            value = math.sin(phase)
        elif kind == 1:  # warm felt-piano note
            value = .94 * math.sin(phase) + .06 * math.sin(phase * 2) * math.exp(-t * 12)
        elif kind == 2:  # muted wooden note, no metallic overtones
            value = .96 * math.sin(phase) + .04 * math.sin(phase * 3) * math.exp(-t * 28)
        else:           # soft lullaby fifth, slowly blooming
            bloom = math.sin(min(1, t / .16) * math.pi / 2) ** 2
            value = .85 * math.sin(phase) + .15 * bloom * math.sin(phase * 1.5)
        out.append(round(10000 * envelope * value))
    return out


def main():
    words = (ROOT / 'assets/words.txt').read_text().split()
    assert words == sorted(set(words)) and all(w.isascii() and w.isalpha() for w in words)
    out = ROOT / 'src/generated'
    out.mkdir(parents=True, exist_ok=True)
    header = ['#pragma once', '#include <cstddef>', '#include <cstdint>',
              'namespace toy {',
              'struct Clip { const int16_t* data; size_t samples; };',
              'struct WordAudio { const char* word; Clip clip; };',
              'extern const WordAudio kWords[];', 'extern const size_t kWordCount;',
              'extern const Clip kEffects[20];', '}']
    (ROOT / 'include/audio_assets.h').write_text('\n'.join(header) + '\n')
    source = ['// Generated by scripts/generate_audio.py; do not edit.',
              '#include "audio_assets.h"', 'namespace toy {']
    manifest = {'voice': 'Samantha', 'rate_wpm': SPEECH_RATE,
                'speech_gain': SPEECH_GAIN, 'sound_palette': 'gentle-v1',
                'sample_rate': RATE, 'words': {}}
    counts = {}
    with tempfile.TemporaryDirectory(prefix='cardputer-audio-') as temp:
        for word in words:
            aiff, raw = Path(temp) / f'{word}.aiff', Path(temp) / f'{word}.pcm'
            run(['say', '-v', 'Samantha', '-r', str(SPEECH_RATE), '-o', str(aiff), word])
            run(['ffmpeg', '-v', 'error', '-y', '-i', str(aiff), '-af',
                 'silenceremove=start_periods=1:start_threshold=-45dB:start_silence=0.025,areverse,silenceremove=start_periods=1:start_threshold=-45dB:start_silence=0.08,areverse,'
                 f'lowpass=f=5500,alimiter=limit=0.75:level=false,volume={SPEECH_GAIN},afade=t=in:d=0.012',
                 '-ar', str(RATE), '-ac', '1', '-f', 's16le', str(raw)])
            data = raw.read_bytes()
            samples = array.array('h', data)
            if sys.byteorder != 'little': samples.byteswap()
            if len(samples) < 1600 or max(map(abs, samples), default=0) < 200:
                raise RuntimeError(f'{word}: empty or silent speech; run with macOS speech service access')
            counts[word] = emit_pcm(out / f'{word}.inc', f'audio_{word}', samples)
            source.append(f'#include "{word}.inc"')
            manifest['words'][word] = {'samples': len(samples), 'sha256_pcm': hashlib.sha256(data).hexdigest()}
            print(f'{word}: {len(samples) / RATE:.2f}s', flush=True)
    effects = []
    for kind in range(4):
        for note in range(5):
            index = kind * 5 + note
            count = emit_pcm(out / f'effect_{index}.inc', f'effect_{index}', effect(kind, note))
            effects.append(count)
            source.append(f'#include "effect_{index}.inc"')
    source.append('const WordAudio kWords[] = {')
    source.extend(f'{{"{w}", {{audio_{w}, {counts[w]}}}}},' for w in words)
    source += ['};', 'const size_t kWordCount = sizeof(kWords) / sizeof(kWords[0]);', 'const Clip kEffects[20] = {']
    source.extend(f'{{effect_{i}, {n}}},' for i, n in enumerate(effects))
    source += ['};', '}']
    (out / 'audio_assets.cpp').write_text('\n'.join(source) + '\n')
    (ROOT / 'assets/audio_manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')


if __name__ == '__main__': main()
